spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

        # Reduce connection pool size
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1


#spring.datasource.url=jdbc:mysql://localhost:3306/resume_review
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


groq.api.key=${GROQ_API_KEY}
spring.web.resources.static-locations=classpath:/static/
server.port=${PORT:8080}